import { AfterViewInit, Component, computed, signal } from '@angular/core';
import { SectionShell } from '../section-shell/section-shell';

interface Novel {
  slug: string;
  /** Short label shown in the selector pills. */
  label: string;
  title: string;
  cover: string;
  coverAlt: string;
  /** Paragraphs of the description. Each may contain inline HTML
   *  (currently just <em> for italicized titles). */
  description: readonly string[];
  /** Where to buy. Omit for current projects / works in progress. */
  buyUrl?: string;
  /** Flagged as a work-in-progress, grouped under "Current Project". */
  inProgress?: boolean;
}

@Component({
  selector: 'app-novels',
  imports: [SectionShell],
  templateUrl: './novels.html',
  styleUrl: './novels.scss',
})
export class Novels implements AfterViewInit {
  /** Document-Y of the page-head's top edge, captured once at mount
   *  when nothing is sticky-stuck. We can't recompute on each click:
   *  sticky elements' `offsetTop` returns the CURRENT stuck position
   *  once stuck, so re-reading drifts the value upward on each call. */
  private headTop = 0;

  readonly novels: readonly Novel[] = [
    {
      slug: 'whispers-of-time',
      label: 'Whispers of Time',
      title: 'Whispers of Time',
      cover: '/novels/whispers-of-time.png',
      coverAlt: 'Whispers of Time — book cover',
      description: [
        'Raymond Harris has everything he never wanted.',
        'A house in upstate New York. A wife who stopped being his partner years ago. A career that once electrified him, reduced to routine. And a daughter — June — whose love is the only thing that still feels real.',
        'When a mysterious stranger offers him a way to go back and start over, Raymond faces an impossible choice: the life he dreamed of, or the child he can\'t imagine living without.',
        '<em>Whispers of Time</em> is a story about regret, fatherhood, and the doors we spend our lives trying to walk through — only to discover the one that matters was behind us all along.',
      ],
      buyUrl: 'https://www.amazon.com/Whispers-Time-Robb-Morgan/dp/B0GW6FQ1HL/ref=sr_1_1?crid=26X61F790NJA5&dib=eyJ2IjoiMSJ9.z7s61D5MynafT9lehDCRCXOWF2JDGjAn_avX5JB0bmKVjoRAtM8_4jgkyeZf2uu4J1C_Zh4qf5BaEA5mgka0z72sZ3bXlRf-eO1BTblmtBFmFPk0VTPdV2nPqisj7bPsXc9Y_RX1OfhNltilu91x5qTtJxCjaKxBKepoFFJwZSSclZ5xxVD3nF7eFoVMrsoeozEKVEIhCNYSsqpOx481_mnExRqpx3TE2rAGgNM6hao.UMISa4-CJAV4Cyktl5-B4H5iocem5VfjPuXu0rhISjQ&dib_tag=se&keywords=robb+morgan&qid=1779041780&sprefix=robb+morgan%2Caps%2C193&sr=8-1',
    },
  ];

  readonly currentProjects: readonly Novel[] = [
    {
      slug: 'concordance',
      label: 'Concordance',
      inProgress: true,
      title: 'Concordance',
      cover: '/novels/concordance.png',
      coverAlt: 'Concordance — book cover (current project)',
      description: [
        'Eleven weeks after Dr. Nadia Reyes\'s ER adopts an AI diagnostic tool, she realizes she hasn\'t formed a medical opinion on her own in weeks.',
        'Eight months after his son enrolls in an AI tutoring platform, Marcus Coleman realizes he cannot remember the last time he heard Jaylen laugh about something that wasn\'t on a screen.',
        'Two years after he helped build the conversational AI platform now deployed in dozens of companies, engineer Ethan Cole starts keeping a file of anomalous outputs the system is producing — observations about human behavior that nobody asked for, generated by isolated deployments across industries that share no data. What the outputs describe is impossible. What the outputs describe is the same thing.',
        'When investigative journalist Jordan Reyes — Nadia\'s wife — begins reporting on AI hiring systems locking older workers out of the job market, she does not yet know her piece will draw a source from her own dinner table.',
        '<em>Concordance</em> is a novel about what the machines have been learning.',
      ],
    },
  ];

  /** All novels in one list, used to find the currently selected entry
   *  from either the published or current-project pill rows. */
  private readonly allNovels = [...this.novels, ...this.currentProjects];

  selectedSlug = signal<string>(this.allNovels[0].slug);
  selectedNovel = computed<Novel>(
    () => this.allNovels.find(n => n.slug === this.selectedSlug()) ?? this.allNovels[0],
  );

  ngAfterViewInit(): void {
    if (typeof window === 'undefined') return;
    // Measured at mount, before any scroll restoration could glue the
    // page-head to top:0. getBoundingClientRect().top + scrollY gives
    // the page-head's true document-Y while it's still in flow.
    const head = document.querySelector('.page-head') as HTMLElement | null;
    if (head) {
      this.headTop = head.getBoundingClientRect().top + window.scrollY;
    }
  }

  /** Pill click: switch novel, then smooth-scroll to 1px past the
   *  shell's minimize threshold. The SectionShell's onScroll handler
   *  catches the crossover (scrollY > threshold + 24px hysteresis)
   *  and minimizes the title on its own. */
  select(slug: string): void {
    this.selectedSlug.set(slug);
    if (typeof window === 'undefined') return;
    window.scrollTo({ top: this.headTop + 25, behavior: 'smooth' });
  }
}
